# ndarray 的索引 index 與切割 slice

In [6]:
import numpy as np

arr = np.arange(10)
print(arr[0])
print(arr[-1])
print(arr[:3])
print(arr[-3:])

0
9
[0 1 2]
[7 8 9]


In [12]:
import random

random.randint(50,100)

89

In [11]:
np.random.randint(50,101,size=5)
#一口氣建立亂數二維陣列 50組 5個
score = np.random.randint(50,101,size=(50,5))
print(score.size)
print(score.shape)
print(score[0,0])

250
(50, 5)
64


In [15]:
score[:,0]
score[:,0:1]

array([[ 64],
       [ 68],
       [ 86],
       [ 94],
       [ 95],
       [ 75],
       [ 50],
       [ 55],
       [ 68],
       [ 65],
       [ 92],
       [ 78],
       [ 86],
       [ 73],
       [ 60],
       [ 58],
       [ 57],
       [ 84],
       [ 77],
       [ 63],
       [ 65],
       [ 62],
       [ 64],
       [ 80],
       [ 56],
       [ 81],
       [ 79],
       [ 87],
       [ 92],
       [ 52],
       [ 73],
       [ 72],
       [ 65],
       [ 73],
       [ 82],
       [ 63],
       [ 51],
       [ 81],
       [ 91],
       [ 64],
       [ 67],
       [ 52],
       [ 77],
       [ 79],
       [ 68],
       [100],
       [ 51],
       [ 89],
       [ 78],
       [ 52]], dtype=int32)

In [17]:
score[0,:]
score[0:1,:]

array([[64, 64, 97, 62, 93]], dtype=int32)

In [ ]:
np.sum(score,axis = 1)
np.mean(score,axis = 1)

array([76. , 82. , 81.4, 76. , 81. , 80.8, 61. , 68.4, 74. , 77.4, 72.2,
       76.2, 75.4, 72.4, 72.6, 67.4, 71.2, 73.2, 68.2, 77.2, 63.8, 72.4,
       66.6, 81. , 64.6, 73.4, 73.8, 66.6, 71.8, 65. , 75.2, 77.4, 77.6,
       71.8, 68.8, 68.2, 76. , 69.2, 78. , 65. , 68.4, 77. , 69.8, 84. ,
       75.2, 76.4, 74.2, 76.8, 81.8, 70.6])

In [ ]:
#ndarray使用比較運算子
arr = np.random.randn(5)
arr > 0

array([False, False, False,  True, False])

In [ ]:
#將大於 0 的傳出 1 否則傳出 0
np.where(arr > 0,1,0)

array([0, 0, 0, 1, 0])

In [ ]:
#把大於 0 的傳出 1 其餘的傳出原值
np.where(arr > 0,1,arr)

array([-0.76514399, -0.5039068 , -0.90355478,  1.        , -1.08713566])