In [1]:
import numpy as np
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.rand(3,4)

array([[0.695621  , 0.99754885, 0.419722  , 0.44318372],
       [0.52024962, 0.93425038, 0.05325557, 0.48998769],
       [0.55229085, 0.26910486, 0.78633132, 0.38873861]])

In [8]:
scores = np.random.randint(50,101,size=(50,5))