In [3]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[85, 84, 88, 86, 63],
       [56, 73, 84, 70, 89],
       [85, 63, 70, 74, 86],
       [96, 68, 68, 76, 59],
       [95, 78, 73, 84, 93]], dtype=int32)

In [4]:
scores[:3,2:]

array([[88, 86, 63],
       [84, 70, 89],
       [70, 74, 86]], dtype=int32)

In [ ]:
scores[4]
scores[4,:]
scores[4:,:]    #變成二維

array([[95, 78, 73, 84, 93]], dtype=int32)

In [9]:
scores[:,:2]

array([[85, 84],
       [56, 73],
       [85, 63],
       [96, 68],
       [95, 78]], dtype=int32)

### numpy的統計工具

In [10]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 58,  63,  71,  92,  88],
       [ 58,  61,  85,  54,  78],
       [ 82,  94,  51,  61,  96],
       [ 84,  66,  65,  89,  51],
       [ 54,  54,  53,  67, 100]], dtype=int32)

In [11]:
scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

array([372, 336, 384, 355, 328], dtype=int32)

In [ ]:
#加總
np.sum(scores,axis=1)

array([372, 336, 384, 355, 328])

In [ ]:
#平均
np.average(scores,axis=1)

array([74.4, 67.2, 76.8, 71. , 65.6])

In [16]:
#最大
np.max(scores,axis=1)

array([ 92,  85,  96,  89, 100], dtype=int32)

In [17]:
#最小
np.min(scores,axis=1)

array([58, 54, 51, 51, 53], dtype=int32)

In [18]:
#中間數
np.median(scores,axis=1)

array([71., 61., 82., 66., 54.])

In [19]:
#標準差
np.std(scores,axis=1)

array([13.45511055, 12.08966501, 17.92651667, 13.81303732, 17.9621825 ])